package T5;

public class Except {
	
	public int div(int a,int b) throws ArithmeticException
	{
		return a/b;
		/*try{
			return a/b;
			}
		catch (Exception e){
			//e.printStackTrace();
			System.out.println(e.toString());
			return 1;
			}*/
		}
	
	public int fn1(int a,int b) throws ArithmeticException{
		return div(a,b);
		
	}
}


class ExceptTest{
	public static void main(String[] args){
		Except ex = new Except();
		//ex.fn1(10,0);
		try{
			ex.fn1(10,0);
		}
		catch (ArithmeticException e){
			//System.out.println(e.toString());
			e.printStackTrace();
		}
		/*catch (ArithmeticException e){
			//System.out.println(e.toString());
		}*/
		System.out.println("Finsh!");
	}
}
